SET DATABASE SQL SYNTAX ORA TRUE;
DROP SCHEMA IF EXISTS TEST CASCADE;

CREATE SCHEMA TEST;

DROP SEQUENCE IF EXISTS SEQ_T_POETRY;

DROP TABLE IF EXISTS T_POETRY;

CREATE SEQUENCE SEQ_T_POETRY START WITH 1 INCREMENT BY 1;

CREATE TABLE T_POETRY
(
"ID" NUMBER(5, 0) NOT NULL,
"POEM" VARCHAR2(200),
PRIMARY KEY("ID")
)
